// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/YuYang/Documents/baseComponent/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.6_@types+node@25.0.9_@types+react@18.3.27_eslint@8.57.1_less-loa_whglcchrur73oj4mkjkfam6fre/node_modules/dumi/theme-default/slots/Sidebar/index.js';
