// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide":{"path":"guide","id":"docs/guide","parentId":"DocLayout"},"components/alert/README":{"id":"components/alert/README","path":"components/alert","parentId":"DocLayout","meta":{"_atom_route":true}},"components/button/README":{"id":"components/button/README","path":"components/button","parentId":"DocLayout","meta":{"_atom_route":true}},"components/checkbox/README":{"id":"components/checkbox/README","path":"components/checkbox","parentId":"DocLayout","meta":{"_atom_route":true}},"components/input/README":{"id":"components/input/README","path":"components/input","parentId":"DocLayout","meta":{"_atom_route":true}},"components/modal/README":{"id":"components/modal/README","path":"components/modal","parentId":"DocLayout","meta":{"_atom_route":true}},"components/radio-group/README":{"id":"components/radio-group/README","path":"components/radio-group","parentId":"DocLayout","meta":{"_atom_route":true}},"components/select/README":{"id":"components/select/README","path":"components/select","parentId":"DocLayout","meta":{"_atom_route":true}},"components/text-field/README":{"id":"components/text-field/README","path":"components/text-field","parentId":"DocLayout","meta":{"_atom_route":true}},"patterns/form/README":{"id":"patterns/form/README","path":"patterns/form","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/YuYang/Documents/baseComponent/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.6_@types+node@25.0.9_@types+react@18.3.27_eslint@8.57.1_less-loa_whglcchrur73oj4mkjkfam6fre/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'/Users/YuYang/Documents/baseComponent/apps/docs/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/YuYang/Documents/baseComponent/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.6_@types+node@25.0.9_@types+react@18.3.27_eslint@8.57.1_less-loa_whglcchrur73oj4mkjkfam6fre/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide': React.lazy(() => import(/* webpackChunkName: "docs__guide.md" */'/Users/YuYang/Documents/baseComponent/apps/docs/docs/guide.md')),
'components/alert/README': React.lazy(() => import(/* webpackChunkName: "packages__components__alert__README.md" */'/Users/YuYang/Documents/baseComponent/packages/components/alert/README.md')),
'components/button/README': React.lazy(() => import(/* webpackChunkName: "packages__components__button__README.md" */'/Users/YuYang/Documents/baseComponent/packages/components/button/README.md')),
'components/checkbox/README': React.lazy(() => import(/* webpackChunkName: "packages__components__checkbox__README.md" */'/Users/YuYang/Documents/baseComponent/packages/components/checkbox/README.md')),
'components/input/README': React.lazy(() => import(/* webpackChunkName: "packages__components__input__README.md" */'/Users/YuYang/Documents/baseComponent/packages/components/input/README.md')),
'components/modal/README': React.lazy(() => import(/* webpackChunkName: "packages__components__modal__README.md" */'/Users/YuYang/Documents/baseComponent/packages/components/modal/README.md')),
'components/radio-group/README': React.lazy(() => import(/* webpackChunkName: "packages__components__radio-group__README.md" */'/Users/YuYang/Documents/baseComponent/packages/components/radio-group/README.md')),
'components/select/README': React.lazy(() => import(/* webpackChunkName: "packages__components__select__README.md" */'/Users/YuYang/Documents/baseComponent/packages/components/select/README.md')),
'components/text-field/README': React.lazy(() => import(/* webpackChunkName: "packages__components__text-field__README.md" */'/Users/YuYang/Documents/baseComponent/packages/components/text-field/README.md')),
'patterns/form/README': React.lazy(() => import(/* webpackChunkName: "packages__patterns__form__README.md" */'/Users/YuYang/Documents/baseComponent/packages/patterns/form/README.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/YuYang/Documents/baseComponent/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.6_@types+node@25.0.9_@types+react@18.3.27_eslint@8.57.1_less-loa_whglcchrur73oj4mkjkfam6fre/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
