// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"components/button/README":{"id":"components/button/README","path":"components/button","parentId":"DocLayout","meta":{"_atom_route":true}},"components/input/README":{"id":"components/input/README","path":"components/input","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/YuYang/Documents/baseComponent/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.6_@types+node@25.0.9_@types+react@19.2.8_eslint@8.57.1_less-load_ajucnttmevgjt7jyc7dzinbgsu/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'/Users/YuYang/Documents/baseComponent/apps/docs/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/YuYang/Documents/baseComponent/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.6_@types+node@25.0.9_@types+react@19.2.8_eslint@8.57.1_less-load_ajucnttmevgjt7jyc7dzinbgsu/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'components/button/README': React.lazy(() => import(/* webpackChunkName: "packages__button__README.md" */'/Users/YuYang/Documents/baseComponent/packages/button/README.md')),
'components/input/README': React.lazy(() => import(/* webpackChunkName: "packages__input__README.md" */'/Users/YuYang/Documents/baseComponent/packages/input/README.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/YuYang/Documents/baseComponent/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.6_@types+node@25.0.9_@types+react@19.2.8_eslint@8.57.1_less-load_ajucnttmevgjt7jyc7dzinbgsu/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
